# Generated by Django 2.1.5 on 2019-08-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
