# Generated by Django 2.1.5 on 2019-09-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190813_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=None)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.TextField(null=True)),
            ],
        ),
    ]
