# Generated by Django 2.1.5 on 2019-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_ptcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptcases',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ptcases',
            name='max_wait',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='ptcases',
            name='min_wait',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='ptcases',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ptcases',
            name='pthost',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptcases',
            name='result',
            field=models.FileField(default=1, null=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ptcases',
            name='url',
            field=models.URLField(),
        ),
    ]
